### ISSUE TITLE
Syntax Error: redeclaration of let value

### ISSUE THREAD

**Issue by tecnosegugio** [fffilo/gnome-vagrant-indicator#4] opened 2017-10-16 09:44 UTC
With Gnome 3.26.1 (Debian Sid) the extension does not start. 
In Lookin Glass I got the "Syntax Error: redeclaration of let value".

I've checked the sources and I think that the problem is in menu.js, rows 570-577, because there is a double declaration of "value" variable. 
Changing it in "value2" solve the problem.

**Comment by mozky** [comment] 2017-10-24 14:55
I'm having the same issue on Ubuntu 17.10 which comes with GNOME 3.26.1

`oct 24 09:44:03 lentovo gnome-shell[1392]: Extension "gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com" had error: SyntaxError: redeclaration of let value
`

**Comment by dvdknaap** [comment] 2017-11-11 09:56
@mozky 
I can confirm your fix will solve this issue
If you want to fix this issue before the fix is merged just remove 'let' on line 570 in file:
`~/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/menu.js`

Then i rebooted my pc and it works

**Comment by fffilo** [comment] 2017-11-11 11:26
thank you all and sorry for delay. update your extension with

	wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

...and refresh gnome shell (`alt+f2 + r`)

**Comment by dvdknaap** [comment] 2017-11-13 10:10
@fffilo `alt+f2 + r` doesn't work on ubuntu 17.10 and an reboot didnt fixed it.
Maybe release an new version with support of 3.26.1 because it's working

**Closed as completed** 2018-01-05 17:46 UTC
