### ISSUE TITLE
Cannot start a halted box

### ISSUE THREAD

**Issue by lofidevops** [fffilo/gnome-vagrant-indicator#8] opened 2018-11-26 12:19 UTC
**Steps to reproduce:**

* Click on Vagrant indicator
* Hover over halted box

**What should happen:**

* Option start box (`vagrant up`) appears

**What happens instead:**

* No such option

**Notes:**

This would be the equivalent of the following context-less commands:

```
vagrant global-status
# lists boxes with id and status
# note ID of box you want to start, e.g. 25df1ae
vagrant up 25df1ae
```

**Comment by fffilo** [comment] 2018-11-26 16:04
i'm not sure i understand... can you provide some screenshot?

**Comment by lofidevops** [comment] 2018-11-26 17:50
Here's a box appearing in the dropdown, but without an option to "vagrant up"...

![vagrant_dropdown](https://user-images.githubusercontent.com/229415/49032105-7094b000-f1b4-11e8-8b83-1dd31c51b0ec.png)

**Comment by fffilo** [comment] 2018-11-26 18:47
that's very strange. the icon (circle) next to machine indicates the state of machine: poweroff (white), preparing (yellow), running (green), saved (orange) and aborted (red). it should not be black. black is default color which means that the state is unknown, so you don't have `vagrant up` option (because machine is not in poweroff state).

please paste me content of `~/.vagrant.d/data/machine-index/index` (while icon is black).

does this icon color change to white when you execute `vagrant global-status --prune`?

**Comment by lofidevops** [comment] 2018-11-28 13:38
1. When I execute `vagrant global-status --prune` the icon does not change to white.

2. Contents of `~/.vagrant.d/data/machine-index/index` (while icon is black). There are two boxes, vagranttest and test2, the icon is black for both.

```
{"version":1,"machines":{"25df1ae5f1c14f19badb6378c450dc39":{"local_data_path":"/home/user/Documents/vagranttest/.vagrant","name":"default","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/Documents/vagranttest","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}},"9d608ada3d4b4e5facac4b60459be8c4":{"local_data_path":"/home/user/.config/ldh_developer/shipyard/test2/.vagrant","name":"test2","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/.config/ldh_developer/shipyard/test2","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}}}}
```

3. Contents of `~/.vagrant.d/data/machine-index/index` after running `vagrant up 9d608ad` (the icon for `test2` is still black).

```
{"version":1,"machines":{"25df1ae5f1c14f19badb6378c450dc39":{"local_data_path":"/home/user/Documents/vagranttest/.vagrant","name":"default","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/Documents/vagranttest","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}},"9d608ada3d4b4e5facac4b60459be8c4":{"local_data_path":"/home/user/.config/ldh_developer/shipyard/test2/.vagrant","name":"test2","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/.config/ldh_developer/shipyard/test2","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}}}}
```

4. Contents of `~/.vagrant.d/data/machine-index/index` after running `vagrant global-status --prune` (a notice appears that the machine is running, the icon for `test2` is now green).

```
{"version":1,"machines":{"25df1ae5f1c14f19badb6378c450dc39":{"local_data_path":"/home/user/Documents/vagranttest/.vagrant","name":"default","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/Documents/vagranttest","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}},"9d608ada3d4b4e5facac4b60459be8c4":{"local_data_path":"/home/user/.config/ldh_developer/shipyard/test2/.vagrant","name":"test2","provider":"libvirt","state":"running","vagrantfile_name":null,"vagrantfile_path":"/home/user/.config/ldh_developer/shipyard/test2","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}}}}
```

5. Contents of `~/.vagrant.d/data/machine-index/index` after selecting "test2" > "Halt" from the indicator dropdown (a notice appears the the machine "went shutoff", and the icon for `test2` is now black).

```
{"version":1,"machines":{"25df1ae5f1c14f19badb6378c450dc39":{"local_data_path":"/home/user/Documents/vagranttest/.vagrant","name":"default","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/Documents/vagranttest","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}},"9d608ada3d4b4e5facac4b60459be8c4":{"local_data_path":"/home/user/.config/ldh_developer/shipyard/test2/.vagrant","name":"test2","provider":"libvirt","state":"shutoff","vagrantfile_name":null,"vagrantfile_path":"/home/user/.config/ldh_developer/shipyard/test2","updated_at":null,"extra_data":{"box":{"name":"debian/stretch64","provider":"libvirt","version":"9.6.0"}}}}}
```

### Note

For most vagrant commands I am prompted with an administrator prompt saying "System policy prevents management of local virtualized systems". I'm not sure if this is normal, and could be interfering with a non-sudo indicator?

**Comment by fffilo** [comment] 2018-11-28 16:17
the problem is unknown state: in your case _shutoff_. the valid states are (at least i thought was) _poweroff_, _preparing_, _running_, _saved_ and _aborted_. instead _shutoff_ i have _poweroff_ in my index file.

which version of vagrant do you run?

i will add _shutoff_ as valid state and get back to you asap.

**Comment by fffilo** [comment] 2018-11-28 16:30
please update your extension from develop 

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash -s -- develop

...test it and let me know.

**Comment by lofidevops** [comment] 2018-11-28 17:50
I'm using Vagrant 2.1.5 on PureOS 8. I've created an upstream issue to confirm what the state should be, and whether this is version related.

I will let you know as soon as I get a chance to test, thanks!

**Comment by lofidevops** [comment] 2018-11-28 18:07
Speedy response from upstream:

> the state of a guest is determined by the provider that backs it. In this case, the guest is reporting to use libvirt. That project lives [here](https://github.com/vagrant-libvirt/vagrant-libvirt). Perhaps you are used to seeing `poweroff` from the virtualbox provider. Thanks!

I can confirm this is a libvirt guest, hence the new state.

**Comment by lofidevops** [comment] 2018-11-28 18:17
I've tested the update. The initial issue is resolved, but there's a new one :stuck_out_tongue_winking_eye: 

The box now appears with a white dot, and an "Up" option. When I click "Up" I'm given a terminal that produces the same output as `vagrant up`. So far so good!

But, the dot does not go green until I run `vagrant global-status --prune`

If I do this, and then "Halt" via the indicator, the box responds correctly (halt text appears, dot goes white, I can select "Up").

**Additional notes**

* The original issue is resolved. I'm happy to continue in this ticket, or close it and open a new one, whatever suits your workflow.
* If I run `vagrant up 1a2b3c4d` the same problem occurs - no green dot until I run `global-status --prune`
* This all appears related to the libvirt backend. Are you happy to support states from libvirt?
* I'll log an upstream issue because the failure to update the state seems to be independent of the indicator.

**Comment by fffilo** [comment] 2020-05-19 13:45
Not an indicator, but `libvirt` issue, closing...

**Closed as completed by fffilo** 2020-05-19 13:45 UTC
